server:
  port: 8080
  servlet:
    context-path: /api/schneider/v1

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  application:
    name: ms-schneider-snowflake

  data:
    mongodb:
      uri: mongodb://admin:pass@localhost:27017/customerdb?authSource=admin

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

snowflake:
  url: jdbc:snowflake://knivgkl-kjb88780.snowflakecomputing.com 
 # https://knivgkl-kjb88780.snowflakecomputing.com
 #Nota: Recordar agregar datos sensibles a archivo de ambiente .env(Crearlo)
  user: VAMD990828
  password: Lf9FhKLXutY9tEC
  warehouse: COMPUTE_WH
  database: SNOWFLAKE_SAMPLE_DATA
  schema: TPCDS_SF100TCL
  role: ACCOUNTADMIN
  timezone: UTC


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.msvc.invex: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"