server:
  port: 8081
  servlet:
    context-path: /api/schneider/v1

spring:
  application:
    name: ms-schneider-snowflake

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

snowflake:
  url: jdbc:snowflake://knivgkl-kjb88780.snowflakecomputing.com 
 # https://knivgkl-kjb88780.snowflakecomputing.com
  user: ${VAMD990828}
  password: ${Lf9FhKLXutY9tEC}
  warehouse: ${SNOWFLAKE_WAREHOUSE:COMPUTE_WH}
  database: SNOWFLAKE_SAMPLE_DATA
  schema: TPCDS_SF100TCL
  role: ${SNOWFLAKE_ROLE:ACCOUNTADMIN}
  timezone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.msvc.invex: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"